#!/usr/bin/env sh

set -e

curl https://data.source.coop/englacial/ice-sheet-temperature/FullDataSet_Randomized.txt --output data/FullDataSet_Randomized.txt
curl https://data.source.coop/englacial/ice-sheet-temperature/AntarcticaBoreholeData/WAISDivide/waisdivide_imp.csv --output data/waisdivide_imp.csv
